"""Regenerate `streamlit_canary/runtime/static/emoji-shortcodes.js`.

Emoji shortcodes (`:smile:`) are expanded in the browser, by the markdown rule
in `50-markdown.js`, out of the table that file defines. The table is generated
rather than hand-written so the names and the glyphs agree with Streamlit's,
which expands them with remark-emoji over the node-emoji data bundled in its
frontend bundle -- the same data read here.

    python test/gen_emoji_shortcodes.py

In that bundle most entries look like `name:MinifiedConst`, with the record
itself (`{keywords:[...],char:'X',...}`) sitting elsewhere in the same chunk,
and a handful are inline (`name:{...char:'X'}`); both shapes are read. Names
are used exactly as Streamlit exposes them: `+1` / `-1` / `100` included,
keywords such as `thumbsup` *not* (that one only works as `:+1:`).

The output was checked name by name against Streamlit itself -- every one of
the 1570 names rendered in a Streamlit app, the text taken back out of the
DOM, and the two tables compared: identical, no extras, no differences.
"""

import importlib.util
import pathlib
import re
import sys

OUT = (
    pathlib.Path(__file__).resolve().parent.parent
    / 'streamlit_canary'
    / 'runtime'
    / 'static'
    / 'emoji-shortcodes.js'
)
HEADER = """\
/* Emoji shortcodes, as in `:smile:`.
 *
 * Generated by `test/gen_emoji_shortcodes.py` from the node-emoji data
 * Streamlit bundles, so both sides draw the same glyph for a name. Served as
 * its own file, like `markdown-it.js`, to keep the page HTML lean; read by the
 * markdown rule in `50-markdown.js`.
 *
 * Regenerate it after upgrading Streamlit, to pick up new emoji.
 */
window.SC_EMOJI = {
"""
INLINE = re.compile(
    r'([A-Za-z0-9_+\-]+|"[A-Za-z0-9_+\-]+"):\{[^{}]{1,400}?char:`([^`]+)`'
)
CONST = re.compile(r'([A-Za-z0-9_$]+)=\{[^{}]{1,400}?char:`([^`]+)`')
PAIR = re.compile(
    r'([A-Za-z0-9_+\-]+|"[A-Za-z0-9_+\-]+"):([A-Za-z0-9_$]+)(?=[,}])'
)


def find_bundle() -> pathlib.Path:
    spec = importlib.util.find_spec('streamlit')
    if spec is None or spec.origin is None:
        raise SystemExit('streamlit is not installed -- nothing to read')
    root = pathlib.Path(spec.origin).parent / 'static' / 'static' / 'js'
    for path in sorted(root.glob('lib.*.js')):
        if 'fitzpatrick_scale' in path.read_text(
            encoding='utf-8', errors='replace'
        ):
            return path
    raise SystemExit('no emoji data chunk under {}'.format(root))


def build_table(text: str) -> dict:
    # The emoji data object is bounded by `fitzpatrick_scale`, a field every
    # record carries, which keeps the chunk's other module maps out.
    region = text[
        max(0, text.find('fitzpatrick_scale') - 4000) : text.rfind(
            'fitzpatrick_scale'
        )
        + 4000
    ]
    consts = dict(CONST.findall(text))
    table = {name.strip('"'): char for name, char in INLINE.findall(region)}
    for name, ident in PAIR.findall(region):
        if ident in consts:
            table[name.strip('"')] = consts[ident]
    return table


def main() -> int:
    bundle = find_bundle()
    print('reading {}'.format(bundle.name))
    table = build_table(bundle.read_text(encoding='utf-8', errors='replace'))
    if len(table) < 1500:
        raise SystemExit(
            'only {} names -- the bundle changed shape'.format(len(table))
        )
    lines = [
        HEADER,
        ''.join(
            "  '{}': '{}',\n".format(name, table[name])
            for name in sorted(table)
        ),
        '};\n',
    ]
    OUT.write_text(''.join(lines), encoding='utf-8')
    print(
        'wrote {}  ({} names, {} bytes)'.format(
            OUT.name, len(table), OUT.stat().st_size
        )
    )
    for name in ('smile', 'maple_leaf', 'four_leaf_clover', '+1', '-1', '100'):
        print('  {:<18} -> {}'.format(name, table.get(name)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
