[project]
name = "streamlit-canary"
version = "0.3.0a17"
description = "LK-flavored Streamlit components."
authors = [{ name = "Likianta", email = "likianta@foxmail.com" }]
license = "MIT"
# readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "argsense>=1.2.0a6",
    "lk-utils>=3.6.0b14",
    "neoprint>=0.1.0a33",
    "psutil>=7.0.0",
    "pyapp-window>=2.2.3a0",
    "streamlit>=1.58.0; python_version >= '3.10'",
    "streamlit>=1.40.0,<1.50.0; python_version >= '3.9' and python_version < '3.10' and python_version != '3.9.7'",
]

[build-system]
requires = ["hatchling>=1.29.0"]
build-backend = "hatchling.build"

[dependency-groups]
dev = []

# [project.optional-dependencies]
# ...

# [project.scripts]
# ...

[project.urls]
homepage = "https://github.com/likianta/streamlit-canary"

[tool.hatch.build.targets.wheel]
packages = ["streamlit_canary"]

[tool.ruff]
line-length = 80

[tool.ruff.format]
quote-style = "single"
skip-magic-trailing-comma = true

# [tool.ruff.lint]
# extend-select = ["I001"]
# extend-select = ["I001", "E501"]

[tool.ruff.lint.isort]
force-single-line = true
# no-sections = true
relative-imports-order = "closest-to-furthest"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]

# [tool.ty.environment]
# extra-paths = ["./lib"]

[tool.ty.rules]
call-non-callable = "ignore"
invalid-type-form = "ignore"
not-iterable = "ignore"
unresolved-attribute = "ignore"

[tool.uv]
prerelease = "allow"

[[tool.uv.index]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
default = true

[[tool.uv.index]]
name = "likianta"
url = "http://localhost:2191/"
# explicit = true

[tool.uv.sources]
argsense = { index = "likianta" }
lk-utils = { index = "likianta" }
pyapp-window = { index = "likianta" }
