[tool.poetry]
name = "streamlit-canary"
version = "0.1.0b1"
description = ""
homepage = "https://github.com/likianta/streamlit-canary"
authors = ["Likianta <likianta@foxmail.com>"]
# readme = "README.md"
packages = [{ include = "streamlit_canary" }]

[tool.poetry.dependencies]
python = "^3.8"
argsense = ">=0.7.2"
# lk-logger = { version = "^6.0.0a16", source = "likianta" }
lk-utils = { version = "^3.1.3", source = "likianta" }
pyapp-window = { version = "^2.2.0b3", source = "likianta" }
streamlit = [
    { version = "^1.40.0", python = ">=3.8,<3.10,!=3.9.7" },
    { version = "^1.44.0", python = ">=3.10,<4.0" },
]

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "primary"

[[tool.poetry.source]]
name = "likianta"
url = "http://47.102.108.149:2131/"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
