"""Export a project's dependencies to a `requirements.lock` file.

Ported from the reference app's `dependency_manager/export.py`.
"""

import typing as tp

from lk_utils import dedent
from lk_utils import fs
from lk_utils import manipulate_text
from lk_utils import now
from lk_utils import run_cmd_args

from ._types import T


def lock_requirements(
    project_info: T.ProjectInfo,
    include_self: bool = False,
    filename_out: str = 'requirements.lock',
    primary_host: tp.Literal['aliyun', 'tsinghua'] = 'tsinghua',
    secondary_host: str = 'localhost',
) -> None:
    if include_self:
        assert fs.exist(
            '{}/dist/{}-{}-py3-none-any.whl'.format(
                project_info['project_path'],
                project_info['name'].replace('-', '_'),
                project_info['version'],
            )
        )

    package_name = project_info['name']
    project_path = project_info['project_path']
    primary_source_url = {
        'aliyun': 'https://mirrors.aliyun.com/pypi/simple/',
        'tsinghua': 'https://pypi.tuna.tsinghua.edu.cn/simple',
    }[primary_host]
    secondary_source_url = 'http://{}:2131'.format(secondary_host)
    private_packages = frozenset(
        x for x in project_info['toml_data']['tool']['uv']['sources']
    )

    def private_package_to_url(package: str, version: str) -> str:
        return '{}/{}/{}-{}-py3-none-any.whl'.format(
            secondary_source_url, package, package.replace('-', '_'), version
        )

    run_cmd_args(
        (
            'uv',
            'export',
            '--format',
            'requirements.txt',
            '--no-hashes',
            '-o',
            filename_out,
            '--frozen',
            '--no-dev',
        ),
        cwd=project_path,
    )

    file = '{}/{}'.format(project_path, filename_out)
    text = fs.load(file, 'plain')

    text = (
        manipulate_text(text)
        .cut()
        .find('-e .\n')
        .then_cut()
        .replace('')
        .prepend(
            dedent(
                """
                # This file was auto generated by pyproject-manager.
                # File was updated at {UPDATE_TIME}
                # Use pip to install:
                #   pip install -U -r {FILENAME} --no-deps

                """,
                rstrip=False,
            ).format(UPDATE_TIME=now('y.m.d h:n:s'), FILENAME=filename_out)
        )
        .then_insert(
            dedent(
                """
                --index-url {PRIMARY_SOURCE}
                --extra-index-url {SECONDARY_SOURCE}
                --trusted-host {TRUSTED_HOST}

                """,
                rstrip=False,
            ).format(
                PRIMARY_SOURCE=primary_source_url,
                SECONDARY_SOURCE=secondary_source_url,
                TRUSTED_HOST=secondary_host,
            )
        )
        .then_insert(
            '{} @ {}/{}/{}-{}-py3-none-any.whl\n'.format(
                package_name,
                secondary_source_url,
                package_name,
                package_name.replace('-', '_'),
                project_info['version'],
            )
            if include_self
            else ''
        )
        .end()
        .subx_all(
            r'([-\w]+)==([.\w]+).*',
            lambda x: (
                '{} @ {}'.format(
                    x.group(1), private_package_to_url(x.group(1), x.group(2))
                )
                if x.group(1) in private_packages
                else x.group()
            ),
        )
        .output()
    )

    fs.dump(text, file)
